# Generated by Django 5.0.4 on 2024-04-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='year_joined',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
