# Generated by Django 5.0.4 on 2024-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_beneficiary_year_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='documents_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='institution_details_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='personal_info_updated',
            field=models.BooleanField(default=False),
        ),
    ]
