# Generated by Django 5.0.4 on 2024-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_beneficiary_documents_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='birth_certificate_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
