# Generated by Django 5.0.4 on 2024-04-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_beneficiary_birth_certificate_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='expected_graduation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
