# Generated by Django 5.0.4 on 2024-05-02 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_profile_pic_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 7, 35, 37, 108203, tzinfo=datetime.timezone.utc)),
        ),
    ]
