# Generated by Django 5.0.4 on 2024-05-08 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_donor_national_id_donor_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaidrequest',
            name='fee_statement',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='fee_structure',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='transcript',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 15, 27, 38, 101163, tzinfo=datetime.timezone.utc)),
        ),
    ]
