# Generated by Django 5.0.4 on 2024-05-08 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_financialaidrequest_fee_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaidrequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 15, 38, 24, 232647, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='fee_statement',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='fee_structure',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='transcript',
            field=models.TextField(default=None, null=True),
        ),
    ]
