# Generated by Django 5.0.4 on 2024-05-24 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_financialaidrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaidrequest',
            name='bursary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='is_orphan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='others',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='proof_of_background',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='scholarships',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=100),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='well_wishers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 3, 52, 42, 76102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='disability_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='funding_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='parent_disability_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='reason_for_aid',
            field=models.TextField(),
        ),
    ]
