# Generated by Django 5.0.4 on 2024-05-24 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_financialaidrequest_bursary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaidrequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 4, 40, 3, 733448, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=100),
        ),
    ]
