# Generated by Django 5.0.4 on 2024-05-24 05:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_financialaidrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaidrequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 5, 21, 13, 324110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
