# Generated by Django 5.0.4 on 2024-05-25 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 25, 8, 22, 33, 332509, tzinfo=datetime.timezone.utc)),
        ),
    ]
